apiVersion: v1
kind: Pod
metadata:
  name: static-web
  lables:
    role: nginx
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP