apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello-ns
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0