apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels: mi-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.1
          ports:
            - containerPort: 80