apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        ports:
        - containerPort: 80


#The Deployment "php-apache" is invalid: spec.template.metadata.labels: 
#Invalid value: map[string]string{"run":"php-apache"}: `selector` does not match template `labels`