apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: php-ns
spec:
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        ports:
        - containerPort: 80
