apiVersion: v1
kind: Pod
metadata:
  name: mi-pod
  namespace: mi-ns
  labels:
    role: nginx
spec:
  containers:
    - name: pod
      image: nginx
      ports:
        - name: pod
          containerPort: 80
          protocol: TCP