apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: mi-web
  labels:
    role: nginx
spec:
  containers:
    - name: web
      image: nginx
      ports:
      - name: web
        containerPort: 80
        protocol: TCP