apiVersion: apps/v1
kind: Deployment
metadata:
  name: clase8-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clase8-mesa
  template:
    metadata:
      labels: 
        app: clase8-mesa
    spec:
      containers:
        - name: bulletin-board
          image: bautionorato/bulletin_board:1.0.0
          ports:
            - containerPort: 8080